name: "Go Installer"
description: "Installs and caches Go binaries using 'go install'."
author: "Matt Dowdell"

branding:
  icon: "download"
  color: "blue"

inputs:
  package:
    description: 'The Go package to install.'
    required: true
  version:
    description: 'The Go package version to install.'
    required: false
    default: 'latest'
  version-file:
    description: 'The go.mod file to lookup the version from.'
    required: false
    default: ''

outputs:
  cached:
    description: 'Whether the binary was installed from the cache.'
    value: ${{ steps.cache.outputs.cache-hit == 'true' }}
  name:
    description: 'The name of the installed binary.'
    value: ${{ steps.gather.outputs.name }}
  version:
    description: 'The installed version.'
    value: ${{ steps.gather.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Gather
      id: gather
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const path = require('path');

          const script = require(path.join(process.env.GITHUB_ACTION_PATH, 'gather.js'));
          await script({ core, exec, glob, path });
      env:
        package: ${{ inputs.package }}
        version: ${{ inputs.version }}
        version_file: ${{ inputs.version-file }}

    - name: Cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      id: cache
      with:
        path: ~/go/bin/${{ steps.gather.outputs.name }}
        key: ${{ steps.gather.outputs.key }}

    - name: Install
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        script: |
          const path = require('path');

          const script = require(path.join(process.env.GITHUB_ACTION_PATH, 'install.js'));
          await script({ exec });
      env:
        dir: ${{ steps.gather.outputs.dir }}
        package: ${{ inputs.package }}
        version: ${{ steps.gather.outputs.version }}
